import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";
import SideLeftContent from "./components/sideLeftContent";
import SideRightContent from "./components/sideRightContent";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SideLeftContent />
        <SideRightContent />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
